### ISSUE TITLE
Adicionar la columna Nro C31 en reporte de pagos

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_contabilidad#15]
A requerimiento de la unidad de contabilidad, es necesario adicionar el campo Nro C31 en el Reporte de Pagos, para aquellos registros que esten relacionados a comrpobante, lo que no tengan la relacion mostrar el registro pero el campo C31 en Blanco.

 
![image](https://user-images.githubusercontent.com/18399403/31780414-a61d5206-b4c3-11e7-8184-875cfb347b41.png)

**Comment by rensi4rn** [comment]
Para hacerlo rapido lo puse en producción sin comitear, probalo

**Comment by rensi4rn** [comment]
Ahora recien me doy cuenta que esto debería se un issu de sus tesorería no de contabilidad,
